### ISSUE TITLE
MacOS Terminal window always open

### ISSUE THREAD

**Issue by kruegge82** [owlysk/CodeTimer#1]
Hello,
i try your tool and have one problem, if i start your CodeTimer-mac_x64 file on mac is open via Terminal, and a second window with the code timer app, if i close the terminal windows also the code timer app is close....

you know a way to hide the terminal window?

thanks

**Comment by owlysk** [comment]
Hi, I think it need to be bundle in .app [https://github.com/neutralinojs/neutralinojs/issues/209](https://github.com/neutralinojs/neutralinojs/issues/209) 
Give me few days to try figure it out and I will come back to you.

**Comment by kruegge82** [comment]
yes its right, thank you very much...

**Comment by owlysk** [comment]
Hi,
after some search I figure out how to bundle it. **BUT** application in bundle has read-only access to files (where cache or credentials are located) so you can't update settings or use cache (app may be slower).  I already created issue on [neutralinojs](https://github.com/neutralinojs/neutralinojs/issues/1131) how to handle this issue in future.

For now, you have to manually add credentionals to file ```setting.neustorage``` to make it work. This file is located in hidden folder ```.storage```
```
CodeTimer-apple.app
    └── Contents
        ├── Info.plist
        ├── MacOS
        │   ├── booter
        │   └── CodeTimer
        └── Resources
            ├── app.icns
            ├── .DS_Store
            ├── extensions
            ├── favicon.ico
            ├── icons
            │   ├── app.icns
            │   ├── appIcon.png
            │   └── trayIcon.png
            ├── neutralino.config.json
            ├── resources
            │   ├── detail.html
            │   ├── .DS_Store
            │   ├── icons
            │   ├── index.html
            │   ├── js
            │   ├── lib
            │   ├── setting.html
            │   └── style.css
            ├── .storage
            │   ├── cache.neustorage
            │   └── setting.neustorage <--- this file need to be changed
            └── .tmp
                └── tray_icon_linux.png


```
Here is a bundle for Mac OS:
[CodeTimer-apple.app.zip](https://github.com/owlysk/CodeTimer/files/12003651/CodeTimer-apple.app.zip)

I hope this will work for you

**Comment by owlysk** [comment]
Hi again. Can you please test this app bundle?
[CodeTimer.app.zip](https://github.com/owlysk/CodeTimer/files/13697687/CodeTimer.app.zip)

Please let me know, if it works.
Thank you

**Comment by kruegge82** [comment]
yes it works very well...

**Comment by owlysk** [comment]
Great, thanks.
