### ISSUE TITLE
It does not connect

### ISSUE THREAD

**Issue by gerroon** [owlysk/CodeTimer#13]
Hi

I have setup the api but it does not connect, what am I doing wrong?  I use Kimai 2.21 on Debian, the web version naturally . works.  Kimari is served in a local network like "http://192.168.1.100:8000"

![image](https://github.com/user-attachments/assets/26c80c8a-8773-4471-9e45-fd8bfd2c9f69)

![image](https://github.com/user-attachments/assets/867410ec-5f43-427e-808a-05bb2e37b91c)

And
![image](https://github.com/user-attachments/assets/34b8cf90-82ae-4637-b194-95e3ff80ed02)

**Comment by owlysk** [comment]
Hi,
I think, problem is HOST url address. It shouldn't be ending with `/api`. Try url like `htttp://example:port` and let me know, if its working

EDIT: In your case,  should be `http://192.168.1.100:8000`

**Comment by nepomuc** [comment]
Same error here. Doesn't work, no matter what format I use for the host.

**Comment by owlysk** [comment]
Do you have same version of Kimai (v2.21)?

**Comment by nepomuc** [comment]
> Do you have same version of Kimai (v2.21)?

2.23.0

**Comment by owlysk** [comment]
Are you guys using `tokens` or `passwords` in API setting in kimai?

**Comment by nepomuc** [comment]
Token

**Comment by owlysk** [comment]
Please check this pre-release. Just ignore update notification and in url don't add `/api` - url should be like `http://localhost:8001`
Let me know, if it's work for you now.
[CodeTimer-release.zip](https://github.com/user-attachments/files/17531773/CodeTimer-release.zip)
