### ISSUE TITLE
Focus to input-field if open 

### ISSUE THREAD

**Issue by xstable** [owlysk/CodeTimer#4]
Currently you need to use the mouse to click into the text-field, after you opened an Select-Field.  
![image](https://github.com/owlysk/CodeTimer/assets/1778068/92794165-bfe3-41df-b65f-b96007eec2d4)

Would be nice if the input-field would still be focused if you open such an sub menu.. this way you can immediately start to type the characters to fast find the right entry.

That's the same for all three select-Boxes: 
- Customer
- Project
- Activity

Totally awesome would be to have the fields completely keyboard-based. 
Means, you click with the Mouse into the first description-field and only move on with tab and typing to the rest.
At least on Step 5 you only click enter.

![image](https://github.com/owlysk/CodeTimer/assets/1778068/e91f0c99-a32a-4624-879b-0ccd8f8583f4)

**Comment by owlysk** [comment]
Hi,
thanks for suggestion. I improved keyboard usage in last relase [v 1.0.8](https://github.com/owlysk/CodeTimer/releases/tag/v1.0.8) so check it out. 
After you filter value in select box, you have to press &lt;enter&gt; or &lt;tab&gt; for confirm value and then you can use &lt;tab&gt; for next input.

**Comment by xstable** [comment]
Great, thank you for implementing it so fast. 
One last thing I found. 
If you enter a new Timetrack, you click into the text-field. 
But if you've written something, you need the mouse to press start. There is no way to use tab to jump to the start-button currently. 

![image](https://github.com/owlysk/CodeTimer/assets/1778068/748000cd-42ed-424f-9dad-1f61bdcb7d7c)

Would be awesome, if you could implement that `Tab` jump to the start button, and if user then press `Enter` the task start like it does on mouseclick.

**Comment by owlysk** [comment]
Hi,
thanks for feedback. Your made a great suggestion and implementation was not very difficult.
Here you go [v 1.0.9](https://github.com/owlysk/CodeTimer/releases/tag/v1.0.9) :)

**Comment by xstable** [comment]
Thanks a lot for implementing it so fast. 
Great piece of code. Much better in my opinion as the build-in time-tracker in the web-view.
