### ISSUE TITLE
Scrollbar for easier scrolling

### ISSUE THREAD

**Issue by xstable** [owlysk/CodeTimer#5]
I would love to have an scrollbar to easily scroll longer distances in the view. Currently it's only possible to use the scroll of the mouse.

![image](https://github.com/owlysk/CodeTimer/assets/1778068/47eb7932-0d58-44bd-9e4f-bbe3dbeb173e)

**Comment by owlysk** [comment]
Yeah, I am using GNOME and in GNOME there is a scrollbar, so I didn't know that is missing O:-)
Scrollbar will be added in next version.

Edit:
Added in [v 1.0.10](https://github.com/owlysk/CodeTimer/releases/tag/v1.0.10)
